{% set name = "parallel-ssh" %}
{% set version = "2.16.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c355eb965c8698e7ec8e7fd39fbe1b0d6d35debc2de603ebb1b397a9bc30d61c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - gevent >=1.3.0
    - ssh2-python
    - ssh-python

test:
  imports:
    - pssh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ParallelSSH/parallel-ssh
  summary: Asynchronous parallel SSH library
  license: GPL-2.0-only AND LGPL-2.1-only
  license_file:
    - COPYING
    - COPYING.LESSER
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
