{% set name = "parallel-ssh" %}
{% set version = "2.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7037db73f59e77ff42a004cfa29b8e3ebfba8c516d03273dbd8423d353e2b005

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gevent >=1.3.0
    - ssh2-python
    - ssh-python

test:
  imports:
    - pssh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ParallelSSH/parallel-ssh
  summary: Asynchronous parallel SSH library
  license: GPL-2.0-only AND LGPL-2.1-only
  license_file:
    - COPYING
    - COPYING.LESSER
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
