{% set name = "parallel-ssh" %}
{% set version = "2.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e4d21a02feb4cfebf58692448d71c0cd14799c40881c5bd6d75aa7d1da4fd0d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - gevent >=1.3.0
    - ssh2-python
    - ssh-python

test:
  imports:
    - pssh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ParallelSSH/parallel-ssh
  summary: Asynchronous parallel SSH library
  license: GPL-2.0-only AND LGPL-2.1-only
  license_file:
    - COPYING
    - COPYING.LESSER
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
