schema_version: 1

context:
  name: parallel-ssh
  version: "2.16.0.post1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: c355eb965c8698e7ec8e7fd39fbe1b0d6d35debc2de603ebb1b397a9bc30d61c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - gevent >=1.3.0
    - ssh2-python
    - ssh-python

tests:
  - python:
      imports:
        - pssh
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Asynchronous parallel SSH library
  license: GPL-2.0-only AND LGPL-2.1-only
  license_file:
    - COPYING
    - COPYING.LESSER
    - LICENSE
  homepage: https://github.com/ParallelSSH/parallel-ssh

extra:
  recipe-maintainers:
    - thewchan
